const products = [
  // Mobile Accessories
  {
    name: "AirPods Pro 2 Copy",
    category: "Mobile Accessories",
    price: 2099,
    description: "High-quality AirPods Pro 2 copy with noise cancellation and touch controls.",
    views: 120,
    colors: [
      { name: "Black", image: "/images/airpodspro2-black.jpg" },
      { name: "White", image: "/images/airpodspro2-white.jpg" },
    ],
  },
  {
    name: "Stereo Earbuds",
    category: "Mobile Accessories",
    price: 1499,
    description: "Clear sound and long battery wireless stereo earbuds.",
    views: 95,
    colors: [{ name: "Default", image: "/images/stereo.jpg" }],
  },
  {
    name: "A9 AirPods",
    category: "Mobile Accessories",
    price: 2499,
    description: "High-quality wireless earbuds with crystal clear sound.",
    views: 410,
    colors: [
      { name: "Black", image: "/images/a9airpodsblack.jpg" },
      { name: "White", image: "/images/a9airpodswhite.jpg" },
    ],
  },
  {
    name: "P9 Headphones",
    category: "Mobile Accessories",
    price: 1799,
    description: "Comfortable over-ear headphones with deep bass.",
    views: 180,
    colors: [
      { name: "Black", image: "/images/p9-black.jpg" },
      { name: "White", image: "/images/p9-white.jpg" },
      { name: "Blue", image: "/images/p9-blue.jpg" },
    ],
  },
  {
    name: "M25",
    category: "Mobile Accessories",
    price: 1599,
    description: "High-performance wireless earbuds with long battery life.",
    views: 230,
    colors: [{ name: "Default", image: "/images/m25.jpg" }],
  },
  {
    name: "M10",
    category: "Mobile Accessories",
    price: 1399,
    description: "Affordable quality earbuds with great sound and comfort.",
    views: 320,
    colors: [{ name: "Default", image: "/images/m10.jpg" }],
  },
  {
    name: "GalaxyBuds 3 Pro",
    category: "Mobile Accessories",
    price: 3199,
    description: "Premium Samsung earbuds with crystal clear audio.",
    views: 150,
    colors: [{ name: "Default", image: "/images/galaxybuds3.jpg" }],
  },
  {
    name: "AirPods Pro Mastercopy",
    category: "Mobile Accessories",
    price: 2699,
    description: "Noise-cancelling wireless earbuds with premium sound.",
    views: 280,
    colors: [
      { name: "Black", image: "/images/airpodsblack.jpg" },
      { name: "White", image: "/images/airpodswhite.jpg" },
    ],
  },

  // Watches
  {
    name: "Arabic Aura",
    category: "Watches",
    price: 1599,
    description: "Stylish Arabic watch with multiple strap colors and elegant design.",
    views: 390,
    colors: [
      { name: "Tiger", image: "/images/watch-tiger.jpg" },
      { name: "White", image: "/images/watch-white.jpg" },
      { name: "Black", image: "/images/watch-black.jpg" },
    ],
  },

{
  name: "Patek Philippe (Rubber Strap)",
  category: "Watches",
  price: 2199,
  description: "Classic Patek Philippe with elegant rubber strap — available in Tiffany, Brown, and Blue colors.",
  views: 180,
  colors: [
    { name: "Tiffany", image: "/images/patekphillipe-tiffany.jpg" },
    { name: "Brown", image: "/images/patekphillipe-brown.jpg" },
    { name: "Blue", image: "/images/patekphillipe-blue.jpg" },
  ],
},
{
  name: "Rolex Couple Watch",
  category: "Watches",
  price: 3499,
  description: "A classy matching set made for couples — available in Black, Golden, and White colors.",
  views: 90,
  colors: [
    { name: "Black", image: "/images/rolexcouple-black.jpg" },
    { name: "Golden", image: "/images/rolexcouple-golden.jpg" },
    { name: "White", image: "/images/rolexcouple-white.jpg" },
  ],
},
{
  name: "Gucci Ladies Watch",
  category: "Watches",
  price: 3799,
  description: "Luxury ladies Gucci watch — available in Golden, Black, Green, and White colors.",
  views: 210,
  colors: [
    { name: "Golden", image: "/images/gucciladies-golden.jpg" },
    { name: "Black", image: "/images/gucciladies-black.jpg" },
    { name: "Green", image: "/images/gucciladies-green.jpg" },
    { name: "White", image: "/images/gucciladies-white.jpg" },
  ],
},
 {
    name: "Rolex Sky Dweller",
    category: "Watches",
    price: 3699,
    description: "Premium watch with sophisticated design for collectors.",
    views: 450,
    colors: [{ name: "Default", image: "/images/rolexskydweller.jpg" }],
  },
  {
    name: "Sabr Watch",
    category: "Watches",
    price: 2899,
    description: "Elegant Sabr watch with black and white dial options.",
    views: 160,
    colors: [
      { name: "Black Dial", image: "/images/sabr-black.jpg" },
      { name: "White Dial", image: "/images/sabr-white.jpg" },
    ],
  },

{
  name: "Rolex Submariner (leather Strap)",
  category: "Watches",
  price: 2499,
  description: "Classic Rolex Submariner with a durable rubber strap — sporty and elegant.",
  views: 200,
  colors: [
    { name: "Blue", image: "/images/rolexsubmarinerblue.jpg" },
    { name: "Black", image: "/images/rolexsubmarinerblack.jpg" },
    { name: "White", image: "/images/rolexsubmarinerwhite.jpg" },
  ],
},
{
  name: "Rolex Land Dweller (Chain)",
  category: "Watches",
  price: 3799,
  description: "Premium Rolex Land Dweller with chain strap — available in multiple Tiffany-inspired colors.",
  views: 180,
  colors: [
    { name: "Green", image: "/images/rolexlanddwellergreen.jpg" },
    { name: "Blue", image: "/images/rolexlanddwellerblue.jpg" },
    { name: "Black", image: "/images/rolexlanddwellerblack.jpg" },
    { name: "White", image: "/images/rolexlanddwellerwhite.jpg" },
    { name: "Tiffany", image: "/images/rolexlanddwellertiffany.jpg" },
  ],
},
{
  name: "Rolex Daytona (silicone  Strap, Chronograph)",
  category: "Watches",
  price: 2999,
  description: "Iconic Rolex Daytona with chronograph feature, available in golden and silver case variants.",
  views: 220,
  colors: [
    { name: "Golden Case", image: "/images/rolexdaytonagolden.jpg" },
    { name: "Silver Case", image: "/images/rolexdaytonasilver.jpg" },
  ],
},
{
  name: "Rolex GMT Master",
  category: "Watches",
  price: 3799,
  description: "Rolex GMT Master with versatile color options — perfect for collectors.",
  views: 250,
  colors: [
    { name: "Black", image: "/images/rolexgmtblack.jpg" },
    { name: "Blue", image: "/images/rolexgmtblue.jpg" },
    { name: "Green", image: "/images/rolexgmtgreen.jpg" },
    { name: "Red", image: "/images/rolexgmtred.jpg" },
    { name: "Silver & Golden Twotone", image: "/images/rolexgmttwotone.jpg" },
  ],
},
{
  name: "Patek Philippe (Chain, Steel Stainless)",
  category: "Watches",
  price: 3499,
  description: "Elegant Patek Philippe with stainless steel chain — available in Tiffany-inspired colors.",
  views: 180,
  colors: [
    { name: "Blue", image: "/images/patekphillipeblue.jpg" },
    { name: "Black", image: "/images/patekphillipeblack.jpg" },
    { name: "Brown", image: "/images/patekphillipebrown.jpg" },
    { name: "Tiffany", image: "/images/patekphillipetiffany.jpg" },
  ],
},// Corrected Rolex Datejust and Tissot Watches
{
  name: "Rolex Datejust (Arabic Dial)",
  category: "Watches",
  price: 3299,
  description: "Rolex Datejust featuring an Arabic dial, available in elegant two-tone options.",
  views: 150,
  colors: [
    { name: "Silver & Black Twotone", image: "/images/rolexdatejustarabicsilverblack.jpg" },
    { name: "Silver & Blue Twotone", image: "/images/rolexdatejustarabicsilverblue.jpg" },
  ],
},
{
  name: "Rolex Datejust",
  category: "Watches",
  price: 3299,
  description: "Classic Rolex Datejust with sleek dial options.",
  views: 140,
  colors: [
    { name: "Blue Dial", image: "/images/rolexdatejust-blue.jpg" },
    { name: "Black Dial", image: "/images/rolexdatejust-black.jpg" },
  ],
},
{
  name: "Tissot PRX Powermatic",
  category: "Watches",
  price: 3199,
  description: "Tissot PRX Powermatic with sleek dial options for a modern, versatile look.",
  views: 120,
  colors: [
    { name: "Black Dial", image: "/images/tissotprxblack.jpg" },
    { name: "Light Blue Dial", image: "/images/tissotprxlightblue.jpg" },
    { name: "White Dial", image: "/images/tissotprxwhite.jpg" },
  ],
},
{
  name: "Hublot (Stainless Steel Chain)",
  category: "Watches",
  price: 3499,
  description: "Stylish Hublot watch with stainless steel chain, available in multiple colors.",
  views: 200,
  colors: [
    { name: "Black", image: "/images/hublotblack.jpg" },
    { name: "Green", image: "/images/hublotgreen.jpg" },
    { name: "White", image: "/images/hublotwhite.jpg" },
    { name: "Brown", image: "/images/hublotbrown.jpg" },
  ],
},
{
  name: "Omega Ladies Watch",
  category: "Watches",
  price: 2499,
  description:
    "Elegant Omega ladies watch with premium design and quartz movement — perfect for daily wear and special occasions.",
  views: 120,
  colors: [{ name: "Default", image: "/images/omegaladies.jpg" }],
},

{
  name: "FT Ladies Watch (Square Dial)",
  category: "Watches",
  price: 2699,
  description: "Chic FT ladies watch with a modern square dial and comfortable strap — classic yet trendy.",
  views: 85,
  colors: [
    { name: "Gold & Silver", image: "/images/ftladiesgoldsilver.jpg" },
    { name: "Silver", image: "/images/ftladiessilver.jpg" },
    { name: "Black", image: "/images/ftladiesblack.jpg" },
    { name: "Gold", image: "/images/ftladiesgold.jpg" },
  ],
},

{
  name: "D-Lon Ladies Watch (Quartz Movement)",
  category: "Watches",
  price: 2299,
  description: "Stylish D-Lon ladies watch featuring a reliable quartz movement and luxurious finish.",
  views: 98,
  colors: [
    { name: "Black", image: "/images/dlonladiesblack.jpg" },
    { name: "Rose Gold & Silver", image: "/images/dlonladiesrosegoldsilver.jpg" },
    { name: "Rose Gold Twotone", image: "/images/dlonladiesrosegoldtwotone.jpg" },
  ],
},
{
  name: "Cartier Ladies Watch (Square Dial)",
  category: "Watches",
  price: 3799,
  description:
    "Elegant Cartier-inspired ladies watch with a signature square dial, Roman numerals, and polish perfect for both casual and formal looks.",
  views: 200,
  colors: [
    { name: "Black Dial", image: "/images/cartier-black.jpg" },
    { name: "White Dial", image: "/images/cartier-white.jpg" },
  ],
}, 
  {
    name: "Alfajr Watch",
    category: "Watches",
    price: 9999,
    description: "Classic Alfajr Islamic watch with prayer time display.",
    views: 90,
    colors: [{ name: "Default", image: "/images/alfajr.jpg" }],
  },
  {
    name: "Frozen Claw",
    category: "Watches",
    price: 5599,
    description: "Trendy Frozen Claw watch available in multiple striking colors.",
    views: 310,
    colors: [
      { name: "Blue", image: "/images/frozen-blue.jpg" },
      { name: "Green", image: "/images/frozen-green.jpg" },
      { name: "Red", image: "/images/frozen-red.jpg" },
      { name: "Grey", image: "/images/frozen-grey.jpg" },
    ],
  },
];

export default products;